### ISSUE TITLE
[1.12.2] Crash game with TE bee

### ISSUE THREAD

**Issue by Messiah7** [ForestryMC/MagicBees#40]
Hello!
Got a crash with Amped bee in industrial apiary from gendustry mod.
https://pastebin.com/iVPndasA

Then I check in the new world, Amped bee in forestry apiary - same problem.
https://pastebin.com/FrFrhu8v

After crash I cant load world

**UPD:** This happens when bees trying spawn mob from their effect. Amped can spawn Blitz, but if I set effect with the gendustry to "none", then the problem does not repeat.

**Comment by TheFlipflop** [comment]
Got the same problem, any chance it will get fixed soon?

Broken Bees we found so far are Amped, Pyro, Cryo

```
``Thread: Server thread
Stacktrace:
	at magicbees.elec332.corerepack.compat.forestry.allele.AlleleEffectThrottled.isThrottled(AlleleEffectThrottled.java:54)
	at magicbees.elec332.corerepack.compat.forestry.allele.AlleleEffectThrottled.doEffect(AlleleEffectThrottled.java:42)
	at forestry.apiculture.genetics.Bee.doEffect(Bee.java:187)
	at forestry.apiculture.genetics.Bee.doEffect(Bee.java:168)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:275)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TileApiary.scala:137)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at net.bdew.gendustry.misc.DataSlotErrorStates.withSuspendedUpdates(DataSlotErrorStates.scala:80)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:129)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
	at net.bdew.gendustry.machines.apiary.TileApiary.func_73660_a(TileApiary.scala:44)

-- Block entity being ticked --
Details:
	Name: gendustry:industrial_apiary // net.bdew.gendustry.machines.apiary.TileApiary
	Block type: ID #1149 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-2059,41,-972), Chunk: (at 5,2,4 in -129,-61; contains blocks -2064,0,-976 to -2049,255,-961), Region: (-5,-2; contains chunks -160,-64 to -129,-33, blocks -2560,0,-1024 to -2049,255,-513)
	Actual block type: ID #1149 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)``
```

**Comment by Nhawks1717** [comment]
Just wanted to add to this issue. I'm also getting this crash with a Smouldering queen. Tested in an industrial apiary as well as an alveary. Copied below are the crash reports for both.

Industrial Apiary:
```
Time: 12/13/17 10:50 AM
Description: Ticking block entity

java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:295)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TileApiary.scala:137)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at net.bdew.gendustry.misc.DataSlotErrorStates.withSuspendedUpdates(DataSlotErrorStates.scala:80)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:129)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
	at net.bdew.gendustry.machines.apiary.TileApiary.func_73660_a(TileApiary.scala:44)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:295)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TileApiary.scala:137)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at net.bdew.gendustry.misc.DataSlotErrorStates.withSuspendedUpdates(DataSlotErrorStates.scala:80)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:129)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
	at net.bdew.gendustry.machines.apiary.TileApiary.func_73660_a(TileApiary.scala:44)

-- Block entity being ticked --
Details:
	Name: gendustry:industrial_apiary // net.bdew.gendustry.machines.apiary.TileApiary
	Block type: ID #1123 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1271,33,82), Chunk: (at 7,2,2 in 79,5; contains blocks 1264,0,80 to 1279,255,95), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Actual block type: ID #1123 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
```

Alveary:
```
Time: 12/13/17 11:00 AM
Description: Exception in server tick loop

java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:295)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at forestry.apiculture.multiblock.AlvearyController.updateServer(AlvearyController.java:233)
	at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:445)
	at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:81)
	at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:31)
	at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1673_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```
