### ISSUE TITLE
Incompatibility issue?

### ISSUE THREAD

**Issue by TheXTrunner** [ForestryMC/MagicBees#95]
https://github.com/Zokonius/planar-artifice/issues/75#issue-1149450373
Was said to get my report here

**Comment by TheXTrunner** [comment]
tested with only a few mods here, still getting some weird errors

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   Planar Artifice Coremod (planarartifice-1.4.0-pre7.jar)
> Contact their authors BEFORE contacting forge
> 
> // There are four lights!
> 
> Time: 6/3/22 1:51 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from §dPla§fnar Art§bifice§8: §2Con§atin§buat§9ion§r (planarartifice)
> Caused by: java.lang.NoSuchFieldError: ASPECT_TIME
> 	at leppa.planarartifice.registry.PAAspects.registerAspects(PAAspects.java:31)
> 	at leppa.planarartifice.main.CommonProxy.preInit(CommonProxy.java:32)
> 	at leppa.planarartifice.client.ClientProxy.preInit(ClientProxy.java:58)
> 	at leppa.planarartifice.main.PlanarArtifice.preInit(PlanarArtifice.java:121)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 309759056 bytes (295 MB) / 1199570944 bytes (1144 MB) up to 5339348992 bytes (5092 MB)
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5728m -Xms256m
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2860 9 mods loaded, 9 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID             | Version      | Source                           | Signature                                |
> 	|:----- |:-------------- |:------------ |:-------------------------------- |:---------------------------------------- |
> 	| LCH   | minecraft      | 1.12.2       | minecraft.jar                    | None                                     |
> 	| LCH   | mcp            | 9.42         | minecraft.jar                    | None                                     |
> 	| LCH   | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCH   | forge          | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCH   | baubles        | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
> 	| LCH   | forestry       | 5.8.2.387    | forestry_1.12.2-5.8.2.387.jar    | None                                     |
> 	| LCH   | magicbees      | 1.0          | MagicBees-1.12.2-3.1.10.jar      | None                                     |
> 	| LCH   | thaumcraft     | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar | None                                     |
> 	| LCE   | planarartifice | 1.4.0-pre7   | planarartifice-1.4.0-pre7.jar    | None                                     |
> 
> 	Loaded coremods (and transformers): 
> Planar Artifice Coremod (planarartifice-1.4.0-pre7.jar)
>   leppa.planarartifice.core.PATransformer
> 	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14830 Compatibility Profile Context 21.10.30.11 27.20.21030.11000' Renderer: 'AMD Radeon(TM) Graphics'
